### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by mlefebvre-deblecx** [mybatis/hazelcast-cache#116]
Is it possible to release a new version with the updated dependencies.

Thanks

**Comment by hazendaz** [comment]
Last release was in 2020 at version 1.2.0, what are you specifically looking for?

**Comment by mlefebvre-deblecx** [comment]
> Last release was in 2020 at version 1.2.0, what are you specifically looking for?

All the dependencies update to the new version of hazelcast

**Comment by hazendaz** [comment]
Will release a new one in a few weeks.  Working in mybatis parent to all subprojects is taking some time and there is a minor defect in the parent that requires a subsequent release before doing so.  Half wonder though after looking here if we shouldn't have hazelcast listed in provided scope since it really should be end project already uses it before adding this module.

**Comment by mlefebvre-deblecx** [comment]
I would be a great idea also to be able to provide the HazelcastInstance to the cache insted of hard coding it inside. 

I needed to use other objets in hazelcast for other part of the project but I couldn't reuse the same HazelCastInstance without rewriting some part of the cache.

Thanks

**Comment by mlefebvre-deblecx** [comment]
Any updates on the new version ? Packages changed and can't use with the new version of hazelcast since class are not found.

**Comment by hazendaz** [comment]
Sorry for delay, releases in flight.  Releasing support ranges for each of following since hazelcast still supports..

1.1.x at 3
1.2.x at 4
1.3.x at 5

Will update specifics here once I get this out.

**Comment by hazendaz** [comment]
Released 1.1.3 for hazelcast 3.12.13
Released 1.2.0 for hazelcast 4.2.6 (really any 4 will do and 5 as well).
Released 1.3.0 for hazelcast 5.1.2 (really any 5 will do and 4 as well).

**Comment by mlefebvre-deblecx** [comment]
Thanks!! It fixed my problem :)
